version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: book_sphere_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: book_sphere_server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://admin:password@mongodb:27017/book_sphere?authSource=admin
      - JWT_SECRET=book_sphere_jwt_secret_key_change_in_production
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  # Frontend Web Application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: book_sphere_client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

  # Mobile Application (React Native)
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: book_sphere_mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    depends_on:
      - server
    volumes:
      - ./mobile:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongodb_data: