import React from 'react';
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import './Home.css';

const Home = () => {
  const { user } = useSelector((state) => state.auth);

  return (
    <div className="home">
      <div className="hero">
        <div className="hero-content">
          <h1>Welcome to BookSphere</h1>
          <p>AI-Powered Group-Based Academic E-Book Management System</p>
          {!user ? (
            <div className="hero-buttons">
              <Link to="/login" className="btn btn-primary">
                Get Started
              </Link>
              <Link to="/register" className="btn btn-secondary">
                Sign Up
              </Link>
            </div>
          ) : (
            <div className="hero-buttons">
              <Link to="/dashboard" className="btn btn-primary">
                Go to Dashboard
              </Link>
            </div>
          )}
        </div>
      </div>

      <div className="features">
        <div className="feature">
          <h2>📚 Group-Based Access</h2>
          <p>Share premium books with up to 4 friends for joint access</p>
        </div>
        <div className="feature">
          <h2>🤖 AI-Powered Learning</h2>
          <p>Get summaries, flashcards, and quizzes generated by local AI</p>
        </div>
        <div className="feature">
          <h2>📊 Progress Tracking</h2>
          <p>Monitor your reading habits and compete with friends</p>
        </div>
        <div className="feature">
          <h2>🔒 Secure & Private</h2>
          <p>In-app reading only - no downloads for ultimate protection</p>
        </div>
      </div>

      <div className="how-it-works">
        <h2>How BookSphere Works</h2>
        <div className="steps">
          <div className="step">
            <h3>1. Join or Create Groups</h3>
            <p>Connect with friends and classmates to share premium books</p>
          </div>
          <div className="step">
            <h3>2. Access Premium Content</h3>
            <p>Read academic books with group purchase access</p>
          </div>
          <div className="step">
            <h3>3. Enhance Learning with AI</h3>
            <p>Generate summaries, flashcards, and quizzes offline</p>
          </div>
          <div className="step">
            <h3>4. Track Progress</h3>
            <p>Monitor your reading habits and compete on leaderboards</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;